server:
  port: 8088
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://database:3306/sports_db?useSSL=false&...
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    encoding: UTF-8

# 移除 JPA 配置
# jpa:
#   show-sql: true
#   hibernate:
#     ddl-auto: none
#   properties:
#     hibernate:
#       dialect: org.hibernate.dialect.MySQL8Dialect

# 添加 MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.sports.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: INFO
    com.example.sports: DEBUG
    org.springframework.web: DEBUG
  file:
    name: logs/spring.log 

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mysql-data  # 数据将保存在项目下的mysql-data目录 